name: Metrics Validation

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  setup-dbt-cloud-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.16'

      - name: Install dbt
        run: |
          python -m venv cloud-env
          source cloud-env/bin/activate
          pip install dbt

      - name: Set up dbt Cloud profile
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: |
          mkdir -p ~/.dbt/
          echo "snowflake:" >> ~/.dbt/profiles.yml
          echo " target: dev" >> ~/.dbt/profiles.yml
          echo " outputs:" >> ~/.dbt/profiles.yml
          echo "   dev:" >> ~/.dbt/profiles.yml
          echo "     type: snowflake" >> ~/.dbt/profiles.yml
          echo "     account: $SNOWFLAKE_ACCOUNT" >> ~/.dbt/profiles.yml
          echo "     user: $SNOWFLAKE_USER" >> ~/.dbt/profiles.yml
          echo "     password: ${{ secrets.SNOWFLAKE_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "     role: $SNOWFLAKE_ROLE" >> ~/.dbt/profiles.yml
          echo "     database: $SNOWFLAKE_DATABASE" >> ~/.dbt/profiles.yml
          echo "     warehouse: $SNOWFLAKE_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "     schema: dbt_metrics_ci" >> ~/.dbt/profiles.yml

      - name: Verify dbt Cloud profile
        run: |
          cat ~/.dbt/profiles.yml
          cat ~/.dbt/dbt_cloud.yml
      
      - name: Run Modified Models
        run: |
          source cloud-env/bin/activate
          dbt run -s state:modified
      
      - name: Clone Non-Modified Models
        run: |
          source cloud-env/bin/activate
          dbt clone --exclude state:modified
          
      - name: Run Metricflow Validations
        run: |
          python -m venv core-env
          source core-env/bin/activate
          pip install dbt-core
          pip install dbt-snowflake
          pip install dbt-metricflow
          dbt parse
          mf validate-configs
